# Generate and commit docs into the repo on push.

name: Generate Docs

on: 
  push:
    branches: [ main ]
    #paths: ["packages/*/stories/**", "packages/*/components/**"] # Trigger the action only when files change in the folders defined here

jobs:
  build-and-deploy:
    #concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
          npm install
          npm run docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main # The branch the action should deploy to.
          FOLDER: docs # The folder to grab the built docs files from
          CLEAN: true # Clean out any previous files in the docs folder
          TARGET_FOLDER: docs # The folder to commit the build docs files into
          GIT_CONFIG_NAME: Deploy Bot
          GIT_CONFIG_EMAIL: info@objektlabs.io
          COMMIT_MESSAGE: Auto generated docs